// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ShoesRequest struct {
	Size                 string   `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShoesRequest) Reset()         { *m = ShoesRequest{} }
func (m *ShoesRequest) String() string { return proto.CompactTextString(m) }
func (*ShoesRequest) ProtoMessage()    {}
func (*ShoesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *ShoesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShoesRequest.Unmarshal(m, b)
}
func (m *ShoesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShoesRequest.Marshal(b, m, deterministic)
}
func (m *ShoesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShoesRequest.Merge(m, src)
}
func (m *ShoesRequest) XXX_Size() int {
	return xxx_messageInfo_ShoesRequest.Size(m)
}
func (m *ShoesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShoesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShoesRequest proto.InternalMessageInfo

func (m *ShoesRequest) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "eventbus.UserRequest")
	proto.RegisterType((*ShoesRequest)(nil), "eventbus.ShoesRequest")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2d, 0x4b, 0xcd, 0x2b,
	0x49, 0x2a, 0x2d, 0x56, 0x52, 0xe3, 0xe2, 0x0e, 0x2d, 0x4e, 0x2d, 0x0a, 0x82, 0x48, 0x0b, 0x89,
	0x73, 0xb1, 0x97, 0x16, 0xa7, 0x16, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xb1, 0x81, 0xb8, 0x9e, 0x29, 0x4a, 0x4a, 0x5c, 0x3c, 0xc1, 0x19, 0xf9, 0xa9, 0xc5, 0x30, 0x85,
	0x42, 0x5c, 0x2c, 0xc5, 0x99, 0x55, 0xa9, 0x50, 0x55, 0x60, 0x76, 0x12, 0x1b, 0xd8, 0x70, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x30, 0xa0, 0x96, 0x6d, 0x00, 0x00, 0x00,
}
