// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Face                 string   `protobuf:"bytes,3,opt,name=face,proto3" json:"face,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

type Shoes struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Logo                 string   `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shoes) Reset()         { *m = Shoes{} }
func (m *Shoes) String() string { return proto.CompactTextString(m) }
func (*Shoes) ProtoMessage()    {}
func (*Shoes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Shoes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shoes.Unmarshal(m, b)
}
func (m *Shoes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shoes.Marshal(b, m, deterministic)
}
func (m *Shoes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shoes.Merge(m, src)
}
func (m *Shoes) XXX_Size() int {
	return xxx_messageInfo_Shoes.Size(m)
}
func (m *Shoes) XXX_DiscardUnknown() {
	xxx_messageInfo_Shoes.DiscardUnknown(m)
}

var xxx_messageInfo_Shoes proto.InternalMessageInfo

func (m *Shoes) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Shoes) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Shoes) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "eventbus.UserInfo")
	proto.RegisterType((*Shoes)(nil), "eventbus.Shoes")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2d, 0x4b, 0xcd, 0x2b, 0x49, 0x2a, 0x2d,
	0x56, 0x0a, 0xe1, 0xe2, 0x08, 0x2d, 0x4e, 0x2d, 0xf2, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xe7, 0x62,
	0x07, 0xa9, 0x89, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d,
	0x53, 0x84, 0xa4, 0xb9, 0x38, 0xc1, 0x12, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x29, 0x0e,
	0x90, 0x80, 0x5f, 0x62, 0x6e, 0xaa, 0x90, 0x10, 0x17, 0x4b, 0x5a, 0x62, 0x72, 0xaa, 0x04, 0x33,
	0x58, 0x1c, 0xcc, 0x56, 0x72, 0xe5, 0x62, 0x0d, 0xce, 0xc8, 0x4f, 0x2d, 0x06, 0x49, 0x16, 0x67,
	0x56, 0xa5, 0x82, 0xcd, 0x63, 0x0d, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x0b, 0x8a, 0x32, 0x93,
	0x21, 0x26, 0x31, 0x06, 0x41, 0x38, 0x20, 0x95, 0x39, 0xf9, 0xe9, 0xf9, 0x30, 0x63, 0x40, 0xec,
	0x24, 0x36, 0xb0, 0x6b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x01, 0x6e, 0x7d, 0xbb,
	0x00, 0x00, 0x00,
}
