// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shoes.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShoesRequest struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShoesRequest) Reset()         { *m = ShoesRequest{} }
func (m *ShoesRequest) String() string { return proto.CompactTextString(m) }
func (*ShoesRequest) ProtoMessage()    {}
func (*ShoesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a13ed02888f4881c, []int{0}
}

func (m *ShoesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShoesRequest.Unmarshal(m, b)
}
func (m *ShoesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShoesRequest.Marshal(b, m, deterministic)
}
func (m *ShoesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShoesRequest.Merge(m, src)
}
func (m *ShoesRequest) XXX_Size() int {
	return xxx_messageInfo_ShoesRequest.Size(m)
}
func (m *ShoesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShoesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShoesRequest proto.InternalMessageInfo

func (m *ShoesRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Shoes struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Logo                 string   `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shoes) Reset()         { *m = Shoes{} }
func (m *Shoes) String() string { return proto.CompactTextString(m) }
func (*Shoes) ProtoMessage()    {}
func (*Shoes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a13ed02888f4881c, []int{1}
}

func (m *Shoes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shoes.Unmarshal(m, b)
}
func (m *Shoes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shoes.Marshal(b, m, deterministic)
}
func (m *Shoes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shoes.Merge(m, src)
}
func (m *Shoes) XXX_Size() int {
	return xxx_messageInfo_Shoes.Size(m)
}
func (m *Shoes) XXX_DiscardUnknown() {
	xxx_messageInfo_Shoes.DiscardUnknown(m)
}

var xxx_messageInfo_Shoes proto.InternalMessageInfo

func (m *Shoes) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Shoes) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Shoes) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*ShoesRequest)(nil), "eventbus.ShoesRequest")
	proto.RegisterType((*Shoes)(nil), "eventbus.Shoes")
}

func init() { proto.RegisterFile("shoes.proto", fileDescriptor_a13ed02888f4881c) }

var fileDescriptor_a13ed02888f4881c = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xce, 0xc8, 0x4f,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2d, 0x4b, 0xcd, 0x2b, 0x49, 0x2a,
	0x2d, 0x56, 0x52, 0xe2, 0xe2, 0x09, 0x06, 0x49, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0x09, 0x71, 0xb1, 0x14, 0x67, 0x56, 0xa5, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9,
	0x4a, 0xae, 0x5c, 0xac, 0x60, 0x35, 0xd8, 0x24, 0x41, 0x62, 0x39, 0xf9, 0xe9, 0xf9, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x41, 0x51, 0x66, 0x72, 0xaa,
	0x04, 0xb3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x84, 0x93, 0xc4, 0x06, 0xb6, 0xdb, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x17, 0x8b, 0xf3, 0xb9, 0x8a, 0x00, 0x00, 0x00,
}
